# Generated by Django 4.2.5 on 2023-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кадастровый номер')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кадастровый номер',
                'verbose_name_plural': 'Кадастровые номера',
                'ordering': ['-created'],
            },
        ),
    ]
