# Generated by Django 4.2.5 on 2023-09-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='latitude',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geodata',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
